### ISSUE TITLE
Dumb question: Implementing other scopes like listeners/granting offline access?

### ISSUE THREAD

**Issue by donjae** [miltador/angular-google-signin#1]
_Apologies in advance for the noob question, still kind of new to gapi_

How would I implement other scopes like granting offline access `grantOfflineAccess()`, or adding listeners like `currentUser.listen()` or `isSignedIn.listen()` within your module?

**Comment by miltador** [comment]
@donjae, your question is not directly related to my module but rather to gapi and it's typings.
But I can help you 🙂

First of all, follow steps described in [Usage](https://github.com/miltador/angular-google-signin#usage).
Once you are done with that, you should get your component that has a method `onGoogleSignInSuccess` and receives the event where you can work with gapi, e.g.:

``` node
onGoogleSignInSuccess(event: GoogleSignInSuccess) {
    let googleUser: gapi.auth2.GoogleUser = event.googleUser;

    gapi.auth2.getAuthInstance().grantOfflineAccess({ scope: 'profile_email' })
      .then((response) => { // Promise was not tested but should work
        // your code
      });

    gapi.auth2.getAuthInstance().currentUser.listen((user) => {
        // your code
      });

    gapi.auth2.getAuthInstance().isSignedIn.listen((signedIn) => {
        // your code
      });
  }
```

So, `gapi.auth2.getAuthInstance()` returns `GoogleAuth` object which has all required methods.

Feel free to test and tell me if it works.

**Comment by donjae** [comment]
Thanks so much for the help! Yeah, I was a bit confused on how to use the `gapi` dependency in the package, and wasn't sure incorporating it was a challenge related to your module.

Thanks again for info!
